export const ERROR_CODES = {
  INVALID_IMAGE_TYPE: "INVALID_IMAGE_TYPE",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  COMPRESSION_FAILED: "COMPRESSION_FAILED",
  INVALID_COMPRESSION_OPTIONS: "INVALID_COMPRESSION_OPTIONS",
  INVALID_VIDEO_TYPE: "INVALID_VIDEO_TYPE",
  VIDEO_TOO_LARGE: "VIDEO_TOO_LARGE",
  VIDEO_TOO_LONG: "VIDEO_TOO_LONG",
  VIDEO_COMPRESSION_FAILED: "VIDEO_COMPRESSION_FAILED",
  INVALID_VIDEO_COMPRESSION_OPTIONS: "INVALID_VIDEO_COMPRESSION_OPTIONS",
  VIDEO_DOWNLOAD_NOT_FOUND: "VIDEO_DOWNLOAD_NOT_FOUND",
  INVALID_REQUEST: "INVALID_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
